apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: my_apps/
    repoURL: https://github.com/amadouth6/Stage.git/
    targetRevision: helmv1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
