apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv-helm
  namespace: helm
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-data-pv-helm
  local:
    path: /srv/softwareheritage-kube/dev/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            # TODO adapt for your needs
            - key: kubernetes.io/os
              operator: In
              values:
                - linux